In [1]:
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt

In [2]:
colors = ['red', 'blue', 'green', 'yellow', 'white']
for color in colors:
    print(color)

red
blue
green
yellow
white


In [3]:
dict_list = [
    {"name": "ゆい", "age": 26},
    {"name": "たけし", "age": 30},
    {"name": "あかり", "age": 22}
]

for d in dict_list:
    for k, v in d.items():
        print(f"{k}: {v}")

name: ゆい
age: 26
name: たけし
age: 30
name: あかり
age: 22


['filename1', 'filenam2', 'filename3']
　→　
['filename1_0.png', 'filenam2_1.png', 'filename3_2.pmnmg']

In [4]:
#これは最低限の例
def add_png(filename_list):

    result_list = []
    
    for idx, filename in enumerate(filename_list):
        result_list.append(filename + '_' + str(idx) + '.png')

    return result_list

In [5]:
file_list = ['filename1', 'filenam2', 'filename3'] 
add_png(file_list)

['filename1_0.png', 'filenam2_1.png', 'filename3_2.png']

In [6]:
#模範解答
def add_png(filename_list):
    '''
    各ファイル名にインデックス番号と拡張子 .png を付けた新しいリストを作成する。

    Args:
        filename_list (list of str): ファイル名のリスト（拡張子なし）

    Returns:
        list of str: 元のファイル名に "_番号.png" を付けたリスト
                     例: ['file1', 'file2'] -> ['file1_0.png', 'file2_1.png']
    '''

    result_list = []
    
    for idx, filename in enumerate(filename_list):
        result_list.append(f"{filename}_{idx}.png")

    return result_list

In [7]:
file_list = ['filename1', 'filenam2', 'filename3'] 
add_png(file_list)

['filename1_0.png', 'filenam2_1.png', 'filename3_2.png']

In [8]:
#リスト内包表記
def add_png(filename_list):
    return [f"{name}_{i}.png" for i, name in enumerate(filename_list)]

file_list = ['filename1', 'filenam2', 'filename3'] 
add_png(file_list)

['filename1_0.png', 'filenam2_1.png', 'filename3_2.png']

# Numpy

In [9]:
np.array([1, 2, 3])

array([1, 2, 3])

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
matrix[0]

array([1, 2, 3])

In [12]:
matrix[0][2]

np.int64(3)

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
type(ndarray[0][0])

numpy.float64

In [15]:
ndarray.astype(np.uint8)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [16]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#numpyならこのような計算が可能
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
ndarray.shape

(3, 2)

In [22]:
ndarray = ndarray.reshape(2,3)
ndarray

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
ndarray.shape

(2, 3)

In [24]:
ndarray = ndarray.reshape(3,2)
np.expand_dims(ndarray, axis=0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [25]:
expand_ndarry = np.expand_dims(ndarray, axis=0)
np.squeeze(expand_ndarry)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
flat_ndarray = np.expand_dims(ndarray, axis=0)
flat_ndarray.flatten()

array([1, 2, 3, 4, 5, 6])

In [27]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [28]:
ndarray[-1]

np.int64(4)

In [29]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
ndarray[0][1]

np.int64(2)

In [31]:
ndarray[0, 1]  # 0行目の1列目

np.int64(2)

In [32]:
ndarray = np.array([1, 2, 3, 4])

In [33]:
ndarray[1:3]  # 1以上3未満

array([2, 3])

In [34]:
ndarray[:3]  #0から3未満

array([1, 2, 3])

In [35]:
ndarray[1:]  # 1番目から最後まで

array([2, 3, 4])

In [36]:
ndarray[-2]  # 最後から2番目

np.int64(3)

In [37]:
ndarray[:-2]

array([1, 2])

In [38]:
ndarray[-2:]

array([3, 4])

In [39]:
ndarray[:]

array([1, 2, 3, 4])

In [40]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],[13, 14, 15, 16]])

In [41]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
ndarray[:3]  # 0~2行目まで

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
ndarray[3:]  # 3行目以降だけ

array([[13, 14, 15, 16]])

In [44]:
ndarray[:3, 2:]  # 3行目未満かつ、2列目以上

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [45]:
ndarray[:3][2:]  # [:3:]が実行されたあとに[2:]が実行されるため上の行と結果が変わる

array([[ 9, 10, 11, 12]])

# np.arange(), np.linspace(), np.logspace()

In [46]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [47]:
list(range(2, 15, 4))

[2, 6, 10, 14]

In [48]:
np.linspace(0, 10, 11)  # 0から10まで間を11個の数字で埋める

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
np.linspace(0, 10, 5)  # 0から10まで間を5個の数字で埋める

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
np.logspace(0, 3, 10)  # 累乗をリニアにしている

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [51]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [52]:
np.linspace(0, 3, 10, endpoint=False)  # 最後の値が含まれない

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

# zeros(), ones(), eye()

In [53]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.zeros(3)

array([0., 0., 0.])

In [55]:
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.ones(3)

array([1., 1., 1.])

In [57]:
np.ones((5, 4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# np.random

In [60]:
np.random.rand()

0.2483694295555623

In [61]:
np.random.rand(3, 4)

array([[0.69041234, 0.74063616, 0.52694653, 0.6277646 ],
       [0.23669331, 0.83136502, 0.06968526, 0.06448482],
       [0.91723123, 0.39837813, 0.07670843, 0.55271247]])

In [62]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [63]:
np.random.rand()

0.7203244934421581

In [64]:
# 正規分布からランダム
np.random.randn()

-0.5281717522634557

In [65]:
abcde = list(np.random.randn(10))
abcde

[np.float64(-1.0729686221561705),
 np.float64(0.8654076293246785),
 np.float64(-2.3015386968802827),
 np.float64(1.74481176421648),
 np.float64(-0.7612069008951028),
 np.float64(0.31903909605709857),
 np.float64(-0.2493703754774101),
 np.float64(1.462107937044974),
 np.float64(-2.060140709497654),
 np.float64(-0.3224172040135075)]

In [66]:
np.random.normal(100,1)

99.61594564533158

In [67]:
np.random.normal(100,1)

101.13376944233543

In [68]:
np.random.normal(100,1)

98.90010873268596

In [69]:
np.random.randint(10, 100, (2, 3))  # 10以上~100未満

array([[11, 10, 70],
       [91, 18, 98]], dtype=int32)

In [70]:
a = np.arange(0, 100, 1)

In [71]:
np.random.choice(a)

np.int64(13)

In [72]:
np.random.choice(a)

np.int64(47)

# 統計量

In [73]:
std_norm = np.random.randn(3,3)
std_norm

array([[ 0.17133845, -0.44285144,  1.70490377],
       [ 0.92434585, -1.30486124, -0.38057504],
       [-0.74362701, -0.43712177, -0.42645009]])

In [74]:
std_norm.max()

np.float64(1.704903771988004)

In [75]:
np.max(std_norm)

np.float64(1.704903771988004)

In [76]:
std_norm.max(axis=0)

array([ 0.92434585, -0.43712177,  1.70490377])

In [77]:
col_max = std_norm.max(axis=0)
mask = (std_norm == col_max)  # ブロードキャストされるから比較演算をすることができる
mask

array([[False, False,  True],
       [ True, False, False],
       [False,  True, False]])

In [78]:
mask.astype(int)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [79]:
std_norm.min()

np.float64(-1.3048612409805047)

In [80]:
std_norm.argmax()

np.int64(2)

In [81]:
std_norm.flatten()[8]

np.float64(-0.4264500924926471)

In [82]:
std_norm.mean()  # 平均

np.float64(-0.10387761275292326)

In [83]:
np.median(std_norm)  # 中央値

np.float64(-0.4264500924926471)

In [84]:
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after = time.time()
print(f"median sec:{after - before}")  # 計算に意外と時間がかかる

median sec:0.018682479858398438


In [85]:
before = time.time()
np.mean(a)
after = time.time()
print(f"mean sec:{after - before}")

mean sec:0.0033037662506103516


In [86]:
np.std(std_norm)  # 標準偏差

np.float64(0.8604190089746997)

# 数学で使う便利関数

In [91]:
my_sqrt = np.sqrt(16)
int(my_sqrt)

4

In [90]:
np.log(2)

np.float64(0.6931471805599453)

In [94]:
np.exp(1)  # e

np.float64(2.718281828459045)

In [95]:
np.e

2.718281828459045

In [96]:
np.sum([1, 2, 3])

np.int64(6)

In [100]:
array = np.arange(1,11)
np.sum(array)

np.int64(55)

In [103]:
array = array.reshape(2, 5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [104]:
np.sum(array, axis=0)

array([ 7,  9, 11, 13, 15])

In [105]:
np.sum(array, axis=1)

array([15, 40])

In [107]:
array = [1, -2, 3, -4, 5, -6, 7]
np.abs(array)

array([1, 2, 3, 4, 5, 6, 7])

# Nan

In [109]:
np.nan  # 計算できないよ! Float関連でよく出る

nan

In [110]:
a = None
a is None

True

In [ ]:
np,.